/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ticktacktoe;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author AZYSS
 */
public class BoardPanel extends javax.swing.JPanel {
    
    private Image boardImage ;
    private boolean draw012 ;

    /**
     * Creates new form BoardPanel
     */
    public BoardPanel(ArrayList<PlayView> playViews) {
        initComponents();
        //load tip image
        ImageIcon bIcon = new ImageIcon(this.getClass().getResource("/res/pngs/board.png"));
        System.out.println("Icon width = " + bIcon.getIconWidth() + "\nIcon Height = " +bIcon.getIconHeight());
        this.boardImage = bIcon.getImage();
        this.draw012 = false ;
        
        //add the play views
        for(int i = 0; i < playViews.size(); i++){
            this.add(playViews.get(i));
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(300, 300));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new java.awt.GridLayout(3, 3, 10, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
        public void paintComponent(Graphics g){
            super.paintComponent(g);
            
            //draw board background image
            g.drawImage(boardImage, 0, 0, getWidth(), getHeight(), this);
        }
        
}
