/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ticktacktoe;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author AZYSS
 */
public class PlayView extends javax.swing.JButton {
    private String playString ;
    private boolean played ;
    private final int position ;
    private Color drawColor ;
    private Image image ;
    ImageIcon iconX ;
    ImageIcon iconO ;
    ImageIcon iconToDraw ;
    /**
     * Creates new form PlayView
     * @param pos Position of this tile on the board
     */
    public PlayView(int pos) {
        initComponents();
        this.position = pos ;
        this.iconX = new ImageIcon(this.getClass().getResource("/res/pngs/x.png"));
        this.iconO = new ImageIcon(this.getClass().getResource("/res/pngs/o.png"));
    }
    
    /**
     * Gets the position of this PlayView in the 3x3 grid board
     * @return PlayView Position in the grid board.
     */
    protected int getPosition(){
        return this.position ;
    }
    
    /**
     * Method to draw the respective play of the player
     * @param play X or O
     */
    protected void drawPlay(String play){
        this.playString = play ;
        if(play.equalsIgnoreCase("X"))
            iconToDraw = iconX ;
        else
            iconToDraw = iconO ;
        
        this.image = iconToDraw.getImage();
        this.played = true ;
        this.repaint();
    }
    
    protected void resetPlayView(){
        this.played = false ;
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 0, 51));
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(100, 100));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        if(this.played){
            g.drawImage(image, 0, 0, this.getWidth(), this.getHeight(), this);
        }else{
            g.clearRect(0, 0, this.getWidth(), this.getHeight());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
}
