/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ticktacktoe;

/**
 *
 * @author AZYSS
 */
public class StatsBoard extends javax.swing.JPanel {

    /**
     * Creates new form StatsBoard
     */
    public StatsBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        humanWinsCPU_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        humanVsCPU_DrawTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CPU_WinsHumanTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        onlineHomePlayerTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        onlineDrawTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        onlineOpponentTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        twoPlayerXTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        twoPlayerDrawTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        twoPlayerOTextField = new javax.swing.JTextField();
        refreshStatsButton = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "::: One Player Game :::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Batang", 0, 12), new java.awt.Color(153, 153, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel1.setText("Human Wins : ");

        humanWinsCPU_TextField.setEditable(false);
        humanWinsCPU_TextField.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        humanWinsCPU_TextField.setForeground(new java.awt.Color(51, 0, 255));
        humanWinsCPU_TextField.setText("0");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel2.setText("Draws : ");

        humanVsCPU_DrawTextField.setEditable(false);
        humanVsCPU_DrawTextField.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        humanVsCPU_DrawTextField.setForeground(new java.awt.Color(204, 0, 0));
        humanVsCPU_DrawTextField.setText("0");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel3.setText("CPU Wins : ");

        CPU_WinsHumanTextField.setEditable(false);
        CPU_WinsHumanTextField.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        CPU_WinsHumanTextField.setForeground(new java.awt.Color(0, 102, 0));
        CPU_WinsHumanTextField.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(humanWinsCPU_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(humanVsCPU_DrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CPU_WinsHumanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(humanWinsCPU_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(CPU_WinsHumanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(humanVsCPU_DrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "::: Online Game :::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Batang", 0, 12), new java.awt.Color(153, 153, 255))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel4.setText("Your Wins : ");

        onlineHomePlayerTextField.setEditable(false);
        onlineHomePlayerTextField.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        onlineHomePlayerTextField.setForeground(new java.awt.Color(51, 0, 255));
        onlineHomePlayerTextField.setText("0");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel5.setText("Draws : ");

        onlineDrawTextField.setEditable(false);
        onlineDrawTextField.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        onlineDrawTextField.setForeground(new java.awt.Color(204, 0, 0));
        onlineDrawTextField.setText("0");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel6.setText("Opponent Wins : ");

        onlineOpponentTextField.setEditable(false);
        onlineOpponentTextField.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        onlineOpponentTextField.setForeground(new java.awt.Color(0, 102, 0));
        onlineOpponentTextField.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onlineHomePlayerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onlineDrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onlineOpponentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(onlineHomePlayerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(onlineDrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(onlineOpponentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "::: Two Player Game :::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Batang", 0, 12), new java.awt.Color(153, 153, 255))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel7.setText("Player X Wins : ");

        twoPlayerXTextField.setEditable(false);
        twoPlayerXTextField.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        twoPlayerXTextField.setForeground(new java.awt.Color(51, 0, 255));
        twoPlayerXTextField.setText("0");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel8.setText("Draws : ");

        twoPlayerDrawTextField.setEditable(false);
        twoPlayerDrawTextField.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        twoPlayerDrawTextField.setForeground(new java.awt.Color(204, 0, 0));
        twoPlayerDrawTextField.setText("0");

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel9.setText("Player O Wins : ");

        twoPlayerOTextField.setEditable(false);
        twoPlayerOTextField.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        twoPlayerOTextField.setForeground(new java.awt.Color(0, 102, 0));
        twoPlayerOTextField.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoPlayerXTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoPlayerDrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoPlayerOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(twoPlayerXTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(twoPlayerDrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(twoPlayerOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        refreshStatsButton.setText("Refresh Stats");
        refreshStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshStatsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshStatsButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshStatsButton)
                .addGap(4, 4, 4))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshStatsButtonActionPerformed
        // TODO add your handling code here:
        this.refreshAllScores();
    }//GEN-LAST:event_refreshStatsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPU_WinsHumanTextField;
    private javax.swing.JTextField humanVsCPU_DrawTextField;
    private javax.swing.JTextField humanWinsCPU_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField onlineDrawTextField;
    private javax.swing.JTextField onlineHomePlayerTextField;
    private javax.swing.JTextField onlineOpponentTextField;
    private javax.swing.JButton refreshStatsButton;
    private javax.swing.JTextField twoPlayerDrawTextField;
    private javax.swing.JTextField twoPlayerOTextField;
    private javax.swing.JTextField twoPlayerXTextField;
    // End of variables declaration//GEN-END:variables

    protected void setOnePlayerHumanScore(int score){
        this.humanWinsCPU_TextField.setText(Integer.toString(score));
    }
    
    protected void setOnePlayerDrawScore(int score){
        this.humanVsCPU_DrawTextField.setText(Integer.toString(score));
    }
    
    protected void setOnePlayerComputerScore(int score){
        this.CPU_WinsHumanTextField.setText(Integer.toString(score));
    }
    
    protected void setTwoPlayerX_Score(int score){
        this.twoPlayerXTextField.setText(Integer.toString(score));
    }
    
    protected void setTwoPlayerO_Score(int score){
        this.twoPlayerOTextField.setText(Integer.toString(score));
    }
    
    protected void setTwoPlayerDrawScore(int score){
        this.twoPlayerDrawTextField.setText(Integer.toString(score));
    }
    
    protected void setOnlineHomePlayerScore(int score){
        this.onlineHomePlayerTextField.setText(Integer.toString(score));
    }
    
    protected void setOnlineAwayPlayerScore(int score){
        this.onlineOpponentTextField.setText(Integer.toString(score));
    }
    
    protected void setOnlineDrawScore(int score){
        this.onlineDrawTextField.setText(Integer.toString(score));
    }
    
    protected void refreshAllScores(){
        this.setOnlineDrawScore(0);
        this.setOnlineAwayPlayerScore(0);
        this.setOnlineHomePlayerScore(0);
        this.setOnePlayerComputerScore(0);
        this.setOnePlayerDrawScore(0);
        this.setOnePlayerHumanScore(0);
        this.setTwoPlayerDrawScore(0);
        this.setTwoPlayerO_Score(0);
        this.setTwoPlayerX_Score(0);
        
    }

    void updateOnePlayerComputerScore() {
        this.CPU_WinsHumanTextField.setText(Integer.toString( Integer.parseInt(this.CPU_WinsHumanTextField.getText()) + 1)) ;
    }

    void updateOnePlayerDrawScore() {
        this.humanVsCPU_DrawTextField.setText(Integer.toString(Integer.parseInt(this.humanVsCPU_DrawTextField.getText() + 1)));
    }

    void updateTwoPlayerO_Wins() {
        this.twoPlayerOTextField.setText(Integer.toString(Integer.parseInt(this.twoPlayerOTextField.getText() + 1)));
    }
    
    void updateTwoPlayerDrawScore(){
        this.twoPlayerDrawTextField.setText(Integer.toString(Integer.parseInt(this.twoPlayerDrawTextField.getText() + 1)));
        
    }

    void updateTwoPlayerX_Wins() {
        this.twoPlayerXTextField.setText(Integer.toString(Integer.parseInt(this.twoPlayerXTextField.getText()) + 1));
    }

    void updateOnePlayerHumanScore() {
        this.humanWinsCPU_TextField.setText(Integer.toString(Integer.parseInt(this.humanWinsCPU_TextField.getText())+1));
    }
    
    void updateOnlineHomePlayerScore(){
        this.onlineHomePlayerTextField.setText(Integer.toString(Integer.parseInt(this.humanWinsCPU_TextField.getText())+1));
    }
    
    void updateOnlineAwayPlayerScore(){
        this.onlineOpponentTextField.setText(Integer.toString(Integer.parseInt(this.humanWinsCPU_TextField.getText())+1));
    }
    
    void updateOnlineDrawScore(){
        this.onlineDrawTextField.setText(Integer.toString(Integer.parseInt(this.humanWinsCPU_TextField.getText())+1));
    }
}
